// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.um.edu.programacion2.trabajofinal.domain;

import ar.um.edu.programacion2.trabajofinal.domain.JuegoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JuegoIntegrationTest_Roo_Configurable {
    
    declare @type: JuegoIntegrationTest: @Configurable;
    
}
